# Generated by Django 5.1.1 on 2024-10-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=78)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('game', models.CharField(choices=[('jump', 'Long jump'), ('race', 'Race'), ('bb', 'Basket Ball'), ('crick', 'Cricket')], default='jump', max_length=10)),
            ],
        ),
    ]
