# Generated by Django 5.1.1 on 2024-11-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_registration2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration2',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration2',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
